### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by fehguy** [json4s/muster#16]
It seems that the README is not right:

```
I've stopped doing scala, so this project is not going anywhere. feel free to adopt it
```

I propose the following:
- Start doing scala
- Re-write muster in something else
- Fix the README if it's an error

**Comment by casualjim** [comment]
- can't do that unfortunately
- the language I use has this stuff all sorted out
- not an error 

closing this, as I think this issue is fixed with the proposed solution. feel free to reopen should it not be satisfactory.
